package org.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.sistemafinanciero.entity.type.EstadoCheque;

/**
 * Accionista generated by hbm2java
 */
@Entity
@Table(name = "CHEQUE", schema = "C##BDSISTEMAFINANCIERO")
@XmlRootElement(name = "cheque")
@XmlAccessorType(XmlAccessType.NONE)
@NamedQueries({ 
	@NamedQuery(name = Cheque.findChequeByNumeroChequeUnico, query = "SELECT c FROM Cheque c WHERE c.numeroChequeUnico = :numeroChequeUnico"),
	})
public class Cheque implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public final static String findChequeByNumeroChequeUnico = "findChequeByNumeroChequeUnico";	
	
	private BigInteger idCheque;
	private EstadoCheque estado;
	private BigInteger numeroCheque;
	private BigInteger numeroChequeUnico;
	private String tipoDocumento;
	private String numeroDocumento;
	private String persona;
	private BigDecimal monto;

	private Date fechaCambioEstado;
	private Chequera chequera;

	public Cheque() {

	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="CHEQUE_SEQ")
	@SequenceGenerator(name="CHEQUE_SEQ", initialValue=1, allocationSize=1, sequenceName="CHEQUE_SEQ")
	@XmlElement(name = "id")	
	@Id
	@Column(name = "ID_CHEQUE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigInteger getIdCheque() {
		return idCheque;
	}

	public void setIdCheque(BigInteger idCheque) {
		this.idCheque = idCheque;
	}

	@XmlElement
	@Enumerated(EnumType.STRING)
	@Column(name = "ESTADO", nullable = false, columnDefinition="nvarchar2")
	public EstadoCheque getEstado() {
		return estado;
	}

	public void setEstado(EstadoCheque estado) {
		this.estado = estado;
	}

	@XmlElement
	@Column(name = "NUMERO_CHEQUE", nullable = false)
	public BigInteger getNumeroCheque() {
		return numeroCheque;
	}

	public void setNumeroCheque(BigInteger numeroCheque) {
		this.numeroCheque = numeroCheque;
	}

	@XmlElement
	@Column(name = "NUMERO_CHEQUE_UNICO", nullable = false)
	public BigInteger getNumeroChequeUnico() {
		return numeroChequeUnico;
	}

	public void setNumeroChequeUnico(BigInteger numeroChequeUnico) {
		this.numeroChequeUnico = numeroChequeUnico;
	}
	
	@XmlElement
	@Column(name = "TIPO_DOCUMENTO", nullable = false, columnDefinition = "nvarchar2")
	public String getTipoDocumento() {
		return tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@XmlElement
	@Column(name = "NUMERO_DOCUMENTO", nullable = false, columnDefinition = "nvarchar2")
	public String getNumeroDocumento() {
		return numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	@XmlElement
	@Column(name = "PERSONA", nullable = false, columnDefinition = "nvarchar2")
	public String getPersona() {
		return persona;
	}

	public void setPersona(String persona) {
		this.persona = persona;
	}

	@XmlElement
	@Column(name = "MONTO", nullable = false)
	public BigDecimal getMonto() {
		return monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@XmlElement
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_CAMBIO_ESTADO", nullable = false)
	public Date getFechaCambioEstado() {
		return fechaCambioEstado;
	}

	public void setFechaCambioEstado(Date fechaCambioEstado) {
		this.fechaCambioEstado = fechaCambioEstado;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CHEQUERA", nullable = false)
	public Chequera getChequera() {
		return chequera;
	}

	public void setChequera(Chequera chequera) {
		this.chequera = chequera;
	}

}
