package org.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.sistemafinanciero.entity.type.TipoDebeHaber;
import org.sistemafinanciero.entity.type.TipoPersona;

/**
 * Accionista generated by hbm2java
 */
@Entity
@Table(name = "DEBE_HABER", schema = "C##BDSISTEMAFINANCIERO")
@XmlRootElement(name = "debeHaber")
@XmlAccessorType(XmlAccessType.NONE)
@NamedQueries({
        @NamedQuery(name = DebeHaber.findIdMonedaTipoFecha, query = "SELECT d FROM DebeHaber d WHERE d.idMoneda=:idMoneda AND d.tipo=:tipo AND d.fecha = :fecha"),
        @NamedQuery(name = DebeHaber.findTipoFecha, query = "SELECT d FROM DebeHaber d WHERE d.tipo=:tipo AND d.fecha = :fecha ORDER BY d.persona") })
public class DebeHaber implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    public final static String findIdMonedaTipoFecha = "DebeHaber.findIdMonedaTipoFecha";
    public final static String findTipoFecha = "DebeHaber.findTipoFecha";

    private BigInteger idDebehaber;
    private TipoDebeHaber tipo;
    private Date fecha;
    private Date hora;
    private String tipoDocumento;
    private String numeroDocumento;
    private TipoPersona tipoPersona;
    private String persona;
    private String numeroCuenta;
    private BigDecimal monto;
    private BigInteger idMoneda;
    private String denominacionMoneda;
    private String simboloMoneda;

    @XmlElement(name = "id")
    @Id
    @Column(name = "ID_DEBE_HABER")
    public BigInteger getIdDebehaber() {
        return idDebehaber;
    }

    public void setIdDebehaber(BigInteger idDebehaber) {
        this.idDebehaber = idDebehaber;
    }

    @XmlElement
    @Enumerated(EnumType.STRING)
    @Column(name = "TIPO", columnDefinition = "nvarchar2")
    public TipoDebeHaber getTipo() {
        return tipo;
    }

    public void setTipo(TipoDebeHaber tipo) {
        this.tipo = tipo;
    }

    @XmlElement
    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA")
    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @XmlElement
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "HORA")
    public Date getHora() {
        return hora;
    }

    public void setHora(Date hora) {
        this.hora = hora;
    }

    @XmlElement
    @Column(name = "TIPO_DOCUMENTO", columnDefinition = "nvarchar2")
    public String getTipoDocumento() {
        return tipoDocumento;
    }

    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    @XmlElement
    @Column(name = "NUMERO_DOCUMENTO", columnDefinition = "nvarchar2")
    public String getNumeroDocumento() {
        return numeroDocumento;
    }

    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }

    @XmlElement
    @Enumerated(EnumType.STRING)
    @Column(name = "TIPO_PERSONA", columnDefinition = "nvarchar2")
    public TipoPersona getTipoPersona() {
        return tipoPersona;
    }

    public void setTipoPersona(TipoPersona tipoPersona) {
        this.tipoPersona = tipoPersona;
    }

    @XmlElement
    @Column(name = "PERSONA", columnDefinition = "nvarchar2")
    public String getPersona() {
        return persona;
    }

    public void setPersona(String persona) {
        this.persona = persona;
    }

    @XmlElement
    @Column(name = "NUMERO_CUENTA", columnDefinition = "nvarchar2")
    public String getNumeroCuenta() {
        return numeroCuenta;
    }

    public void setNumeroCuenta(String numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }

    @XmlElement
    @Column(name = "MONTO")
    public BigDecimal getMonto() {
        return monto;
    }

    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    @XmlElement
    @Column(name = "ID_MONEDA")
    public BigInteger getIdMoneda() {
        return idMoneda;
    }

    public void setIdMoneda(BigInteger idMoneda) {
        this.idMoneda = idMoneda;
    }

    @XmlElement
    @Column(name = "DENOMINACION_MONEDA", columnDefinition = "nvarchar2")
    public String getDenominacionMoneda() {
        return denominacionMoneda;
    }

    public void setDenominacionMoneda(String denominacionMoneda) {
        this.denominacionMoneda = denominacionMoneda;
    }

    @XmlElement
    @Column(name = "SIMBOLO_MONEDA", columnDefinition = "nvarchar2")
    public String getSimboloMoneda() {
        return simboloMoneda;
    }

    public void setSimboloMoneda(String simboloMoneda) {
        this.simboloMoneda = simboloMoneda;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((idDebehaber == null) ? 0 : idDebehaber.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DebeHaber other = (DebeHaber) obj;
        if (idDebehaber == null) {
            if (other.idDebehaber != null)
                return false;
        } else if (!idDebehaber.equals(other.idDebehaber))
            return false;
        return true;
    }

}
