package org.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Accionista generated by hbm2java
 */
@Entity
@Table(name = "HISTORIAL_PAGO_SOBRE_GIRO_BANC", schema = "C##BDSISTEMAFINANCIERO")
@XmlRootElement(name = "historialPagoSobreGiroBancario")
@XmlAccessorType(XmlAccessType.NONE)
@NamedQueries({

@NamedQuery(name = HistorialPagoSobreGiroBancario.findByIdTransaccionBancaria, query = "SELECT s FROM HistorialPagoSobreGiroBancario s WHERE s.idTransaccionBancaria = :idTransaccionBancaria") })
public class HistorialPagoSobreGiroBancario implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    public final static String findByIdTransaccionBancaria = "HistorialPagoSobreGiroBancario.findByIdTransaccionBancaria";

    private BigInteger idHistorialPagoSobreGiroBancario;

    private SobreGiroBancario sobreGiroBancario;
    private BigInteger idTransaccionBancaria;
    private BigDecimal monto;
    private Date fecha;

    public HistorialPagoSobreGiroBancario() {

    }

    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "HISTORIALPAGOSOBREGIROBANC_SEQ")
    @SequenceGenerator(name = "HISTORIALPAGOSOBREGIROBANC_SEQ", initialValue = 1, allocationSize = 1, sequenceName = "HISTORIALPAGOSOBREGIROBANC_SEQ")
    @XmlElement(name = "id")
    @Id
    @Column(name = "ID_HISTORIAL", unique = true, nullable = false, precision = 22, scale = 0)
    public BigInteger getIdHistorialPagoSobreGiroBancario() {
        return this.idHistorialPagoSobreGiroBancario;
    }

    public void setIdHistorialPagoSobreGiroBancario(BigInteger idHistorialPagoSobreGiroBancario) {
        this.idHistorialPagoSobreGiroBancario = idHistorialPagoSobreGiroBancario;
    }

    @XmlElement(name = "sobreGiroBancario")
    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_SOBRE_GIRO_BANCARIO", nullable = false)
    public SobreGiroBancario getSobreGiroBancario() {
        return sobreGiroBancario;
    }

    public void setSobreGiroBancario(SobreGiroBancario sobreGiroBancario) {
        this.sobreGiroBancario = sobreGiroBancario;
    }

    @XmlElement(name = "idTransaccionBancaria")
    @NotNull
    @Column(name = "ID_TRANSACCION_BANCARIA", precision = 22, scale = 0)
    public BigInteger getIdTransaccionBancaria() {
        return idTransaccionBancaria;
    }

    public void setIdTransaccionBancaria(BigInteger idTransaccionBancaria) {
        this.idTransaccionBancaria = idTransaccionBancaria;
    }

    @XmlElement
    @Column(name = "MONTO", nullable = false, precision = 18)
    public BigDecimal getMonto() {
        return monto;
    }

    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    @XmlElement
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FECHA", nullable = false, length = 7)
    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime
                * result
                + ((idHistorialPagoSobreGiroBancario == null) ? 0 : idHistorialPagoSobreGiroBancario
                        .hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        HistorialPagoSobreGiroBancario other = (HistorialPagoSobreGiroBancario) obj;
        if (idHistorialPagoSobreGiroBancario == null) {
            if (other.idHistorialPagoSobreGiroBancario != null)
                return false;
        } else if (!idHistorialPagoSobreGiroBancario.equals(other.idHistorialPagoSobreGiroBancario))
            return false;
        return true;
    }

}
