package org.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * TransaccionBovedaCaja generated by hbm2java
 */
@Entity
@Table(name = "TRANSACCION_BOVEDA_BOVEDA", schema = "C##BDSISTEMAFINANCIERO")
@XmlRootElement(name = "transaccionbovedaboveda")
@XmlAccessorType(XmlAccessType.NONE)
public class TransaccionBovedaBoveda implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BigInteger idTransaccionBovedaBoveda;
	private Date fecha;
	private Date hora;
	private BigDecimal saldoDisponibleOrigen;
	private BigDecimal saldoDisponibleDestino;
	private int estadoSolicitud;
	private int estadoConfirmacion;

	private HistorialBoveda historialBovedaOrigen;
	private HistorialBoveda historialBovedaDestino;

	private String trabajadorOrigen;
	private String trabajadorDestino;
	private String observacion;

	private Set transaccionBovedaBovedaDetalles = new HashSet(0);

	public TransaccionBovedaBoveda() {
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="TRANSACCIONBOVEDABOVEDA_SEQ")
	@SequenceGenerator(name="TRANSACCIONBOVEDABOVEDA_SEQ", initialValue=1, allocationSize=1, sequenceName="TRANSACCIONBOVEDABOVEDA_SEQ")
	@XmlElement(name = "id")	
	@Id
	@Column(name = "ID_TRANSACCION_BOVEDA_BOVEDA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigInteger getIdTransaccionBovedaBoveda() {
		return idTransaccionBovedaBoveda;
	}

	public void setIdTransaccionBovedaBoveda(BigInteger idTransaccionBovedaBoveda) {
		this.idTransaccionBovedaBoveda = idTransaccionBovedaBoveda;
	}

	@XmlElement
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", nullable = false, length = 7)
	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@XmlElement
	@Column(name = "HORA", nullable = false)
	public Date getHora() {
		return hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@XmlElement
	@Column(name = "SALDO_DISPONIBLE_ORIGEN", nullable = false, precision = 18)
	public BigDecimal getSaldoDisponibleOrigen() {
		return saldoDisponibleOrigen;
	}

	public void setSaldoDisponibleOrigen(BigDecimal saldoDisponibleOrigen) {
		this.saldoDisponibleOrigen = saldoDisponibleOrigen;
	}

	@XmlElement
	@Column(name = "SALDO_DISPONIBLE_DESTINO", nullable = false, precision = 18)
	public BigDecimal getSaldoDisponibleDestino() {
		return saldoDisponibleDestino;
	}

	public void setSaldoDisponibleDestino(BigDecimal saldoDisponibleDestino) {
		this.saldoDisponibleDestino = saldoDisponibleDestino;
	}

	@XmlElement
	@Column(name = "ESTADO_SOLICITUD", nullable = false, precision = 22, scale = 0)
	public boolean getEstadoSolicitud() {
		return (estadoSolicitud == 1 ? true : false);
	}

	public void setEstadoSolicitud(boolean estadoSolicitud) {
		this.estadoSolicitud = (estadoSolicitud ? 1 : 0);		
	}

	@XmlElement
	@Column(name = "ESTADO_CONFIRMACION", nullable = false, precision = 22, scale = 0)
	public boolean getEstadoConfirmacion() {
		return (estadoConfirmacion == 1 ? true : false);
	}

	public void setEstadoConfirmacion(boolean estadoConfirmacion) {
		this.estadoConfirmacion = (estadoConfirmacion ? 1 : 0);
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HISTORIAL_BOVEDA_ORIGEN", nullable = false)
	public HistorialBoveda getHistorialBovedaOrigen() {
		return historialBovedaOrigen;
	}

	public void setHistorialBovedaOrigen(HistorialBoveda historialBovedaOrigen) {
		this.historialBovedaOrigen = historialBovedaOrigen;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HISTORIAL_BOVEDA_DESTINO", nullable = false)
	public HistorialBoveda getHistorialBovedaDestino() {
		return historialBovedaDestino;
	}

	public void setHistorialBovedaDestino(HistorialBoveda historialBovedaDestino) {
		this.historialBovedaDestino = historialBovedaDestino;
	}

	@XmlElement
	@Column(name = "TRABAJADOR_ORIGEN", length = 100, columnDefinition = "nvarchar2")
	public String getTrabajadorOrigen() {
		return trabajadorOrigen;
	}

	public void setTrabajadorOrigen(String trabajadorOrigen) {
		this.trabajadorOrigen = trabajadorOrigen;
	}

	@XmlElement
	@Column(name = "TRABAJADOR_DESTINO", length = 100, columnDefinition = "nvarchar2")
	public String getTrabajadorDestino() {
		return trabajadorDestino;
	}

	public void setTrabajadorDestino(String trabajadorDestino) {
		this.trabajadorDestino = trabajadorDestino;
	}

	@XmlElement
	@Column(name = "OBSERVACION", length = 100, columnDefinition = "nvarchar2")
	public String getObservacion() {
		return observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transaccionBovedaBoveda")
	public Set<TransaccionBovedaBovedaDetalle> getTransaccionBovedaBovedaDetalles() {
		return transaccionBovedaBovedaDetalles;
	}

	public void setTransaccionBovedaBovedaDetalles(Set transaccionBovedaBovedaDetalles) {
		this.transaccionBovedaBovedaDetalles = transaccionBovedaBovedaDetalles;
	}

}
