package org.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlElement;

/**
 * TransaccionBovedaOtro generated by hbm2java
 */
@Entity
@Table(name = "TRANSACCION_BOVEDA_OTRO_VIEW", schema = "C##BDSISTEMAFINANCIERO")
@NamedQueries({ @NamedQuery(name = TransaccionBovedaOtroView.findByIdAgencia, query = "SELECT t FROM TransaccionBovedaOtroView t WHERE t.idAgencia = :idAgencia ") })
public class TransaccionBovedaOtroView implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public final static String findByIdAgencia = "TransaccionBovedaOtroView.findByIdAgencia";

	private BigInteger idTransaccion;

	private BigInteger idAgencia;

	private String entidad;
	private String boveda;

	private Date fecha;
	private Date hora;
	private int estado;
	private String tipoTransaccion;
	private BigDecimal monto;
	private String observacion;

	public TransaccionBovedaOtroView() {
	}

	@XmlElement(name = "id")
	@Id
	@Column(name = "ID_TRANSACCION", unique = true, nullable = false, precision = 22, scale = 0)
	public BigInteger getIdTransaccion() {
		return this.idTransaccion;
	}

	public void setIdTransaccion(BigInteger idTransaccion) {
		this.idTransaccion = idTransaccion;
	}

	@Column(name = "ENTIDAD_DENOMINACION", length = 140, columnDefinition = "nvarchar2")
	public String getEntidad() {
		return this.entidad;
	}

	public void setEntidad(String entidad) {
		this.entidad = entidad;
	}

	@Column(name = "BOVEDA_DENOMINACION", length = 140, columnDefinition = "nvarchar2")
	public String getBoveda() {
		return this.boveda;
	}

	public void setBoveda(String boveda) {
		this.boveda = boveda;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", nullable = false, length = 7)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "HORA", nullable = false)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "MONTO", nullable = false, precision = 18)
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@Column(name = "OBSERVACION", length = 140, columnDefinition = "nvarchar2")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public boolean getEstado() {
		return this.estado == 1;
	}

	public void setEstado(boolean estado) {
		this.estado = (estado == true ? 1 : 0);
	}

	@Column(name = "TIPO_TRANSACCION", nullable = false, length = 40, columnDefinition = "nvarchar2")
	public String getTipoTransaccion() {
		return this.tipoTransaccion;
	}

	public void setTipoTransaccion(String tipoTransaccion) {
		this.tipoTransaccion = tipoTransaccion;
	}

	@Column(name = "ID_AGENCIA", nullable = false)
	public BigInteger getIdAgencia() {
		return idAgencia;
	}

	public void setIdAgencia(BigInteger idAgencia) {
		this.idAgencia = idAgencia;
	}

}
