package org.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TransaccionBovedaOtroDetall generated by hbm2java
 */
@Entity
@Table(name = "TRANSACCION_BOVEDA_OTRO_DETALL", schema = "C##BDSISTEMAFINANCIERO")
public class TransaccionBovedaOtroDetall implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BigInteger idTransaccionBovedaOtroDet;
	private MonedaDenominacion monedaDenominacion;
	private TransaccionBovedaOtro transaccionBovedaOtro;
	private BigInteger cantidad;

	public TransaccionBovedaOtroDetall() {
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="TRANSBOVEDAOTRODETALLE_SEQ")
	@SequenceGenerator(name="TRANSBOVEDAOTRODETALLE_SEQ", initialValue=1, allocationSize=1, sequenceName="TRANSBOVEDAOTRODETALLE_SEQ")
	@Id
	@Column(name = "ID_TRANSACCION_BOVEDA_OTRO_DET", unique = true, nullable = false, precision = 22, scale = 0)
	public BigInteger getIdTransaccionBovedaOtroDet() {
		return this.idTransaccionBovedaOtroDet;
	}

	public void setIdTransaccionBovedaOtroDet(BigInteger idTransaccionBovedaOtroDet) {
		this.idTransaccionBovedaOtroDet = idTransaccionBovedaOtroDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA_DENOMINACION", nullable = false)
	public MonedaDenominacion getMonedaDenominacion() {
		return this.monedaDenominacion;
	}

	public void setMonedaDenominacion(MonedaDenominacion monedaDenominacion) {
		this.monedaDenominacion = monedaDenominacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TRANSACCION_BOVEDA_OTRO", nullable = false)
	public TransaccionBovedaOtro getTransaccionBovedaOtro() {
		return this.transaccionBovedaOtro;
	}

	public void setTransaccionBovedaOtro(TransaccionBovedaOtro transaccionBovedaOtro) {
		this.transaccionBovedaOtro = transaccionBovedaOtro;
	}

	@Column(name = "CANTIDAD", nullable = false, precision = 22, scale = 0)
	public BigInteger getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigInteger cantidad) {
		this.cantidad = cantidad;
	}

}
