package org.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * TransaccionBovedaCajaDetall generated by hbm2java
 */
@Entity
@Table(name = "TRANSACCION_BOVEDA_BOVEDA_D", schema = "C##BDSISTEMAFINANCIERO")
@XmlRootElement(name = "detalleTransaccionBovedaBoveda")
@XmlAccessorType(XmlAccessType.NONE)
public class TransaccionBovedaBovedaDetalle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BigDecimal idTransaccionBovedaBovedaDetalle;
	private MonedaDenominacion monedaDenominacion;
	private TransaccionBovedaBoveda transaccionBovedaBoveda;
	private BigInteger cantidad;

	public TransaccionBovedaBovedaDetalle() {
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="TRANSBOVEDABOVEDADETALLE_SEQ")
	@SequenceGenerator(name="TRANSBOVEDABOVEDADETALLE_SEQ", initialValue=1, allocationSize=1, sequenceName="TRANSBOVEDABOVEDADETALLE_SEQ")
	@XmlTransient
	@Id
	@Column(name = "ID_TRANSACCION_BOVEDA_BOVEDA_D", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTransaccionBovedaBovedaDetalle() {
		return idTransaccionBovedaBovedaDetalle;
	}

	public void setIdTransaccionBovedaBovedaDetalle(BigDecimal idTransaccionBovedaBovedaDetalle) {
		this.idTransaccionBovedaBovedaDetalle = idTransaccionBovedaBovedaDetalle;
	}

	@XmlElement
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA_DENOMINACION", nullable = false)
	public MonedaDenominacion getMonedaDenominacion() {
		return monedaDenominacion;
	}

	public void setMonedaDenominacion(MonedaDenominacion monedaDenominacion) {
		this.monedaDenominacion = monedaDenominacion;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TRANSACCION_BOVEDA_BOVEDA", nullable = false)
	public TransaccionBovedaBoveda getTransaccionBovedaBoveda() {
		return transaccionBovedaBoveda;
	}

	public void setTransaccionBovedaBoveda(TransaccionBovedaBoveda transaccionBovedaBoveda) {
		this.transaccionBovedaBoveda = transaccionBovedaBoveda;
	}

	@XmlElement
	@Column(name = "CANTIDAD", nullable = false, precision = 22, scale = 0)
	public BigInteger getCantidad() {
		return cantidad;
	}

	public void setCantidad(BigInteger cantidad) {
		this.cantidad = cantidad;
	}

}
