package org.model;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;

/**
 * BovedaCajaId generated by hbm2java
 */
@Embeddable
public class BovedaCajaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer idBoveda;
	private Integer idCaja;

	public BovedaCajaId() {
	}

	@NotNull
	@Column(name = "ID_BOVEDA", nullable = false)
	public Integer getIdBoveda() {
		return this.idBoveda;
	}

	public void setIdBoveda(Integer idBoveda) {
		this.idBoveda = idBoveda;
	}

	@NotNull
	@Column(name = "ID_CAJA", nullable = false)
	public Integer getIdCaja() {
		return this.idCaja;
	}

	public void setIdCaja(Integer idCaja) {
		this.idCaja = idCaja;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BovedaCajaId))
			return false;
		BovedaCajaId castOther = (BovedaCajaId) other;

		return ((this.getIdBoveda() == castOther.getIdBoveda()) || (this.getIdBoveda() != null && castOther.getIdBoveda() != null && this.getIdBoveda().equals(castOther.getIdBoveda()))) && ((this.getIdCaja() == castOther.getIdCaja()) || (this.getIdCaja() != null && castOther.getIdCaja() != null && this.getIdCaja().equals(castOther.getIdCaja())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdBoveda() == null ? 0 : this.getIdBoveda().hashCode());
		result = 37 * result + (getIdCaja() == null ? 0 : this.getIdCaja().hashCode());
		return result;
	}

}
