package org.model;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.NaturalId;

/**
 * DetalleHistorialBoveda generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_HISTORIAL_BOVEDA", schema = "BDSISTEMAFINANCIERO")
public class DetalleHistorialBoveda implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BigInteger idDetalleHistorialBoveda;
	private MonedaDenominacion monedaDenominacion;
	private HistorialBoveda historialBoveda;
	private int cantidad;

	public DetalleHistorialBoveda() {
	}

	@Id
	@Column(name = "ID_DETALLE_HISTORIAL_BOVEDA", unique = true, nullable = false)
	public BigInteger getIdDetalleHistorialBoveda() {
		return this.idDetalleHistorialBoveda;
	}

	public void setIdDetalleHistorialBoveda(BigInteger idDetalleHistorialBoveda) {
		this.idDetalleHistorialBoveda = idDetalleHistorialBoveda;
	}

	@NotNull
	@NaturalId
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA_DENOMINACION", nullable = false, foreignKey = @ForeignKey)
	public MonedaDenominacion getMonedaDenominacion() {
		return this.monedaDenominacion;
	}

	public void setMonedaDenominacion(MonedaDenominacion monedaDenominacion) {
		this.monedaDenominacion = monedaDenominacion;
	}

	@NotNull
	@NaturalId
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HISTORIAL_BOVEDA", nullable = false, foreignKey = @ForeignKey)
	public HistorialBoveda getHistorialBoveda() {
		return this.historialBoveda;
	}

	public void setHistorialBoveda(HistorialBoveda historialBoveda) {
		this.historialBoveda = historialBoveda;
	}

	@NotNull
	@Min(value = 0)
	@Column(name = "CANTIDAD", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((historialBoveda == null) ? 0 : historialBoveda.hashCode());
		result = prime * result + ((monedaDenominacion == null) ? 0 : monedaDenominacion.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof DetalleHistorialBoveda))
			return false;
		DetalleHistorialBoveda other = (DetalleHistorialBoveda) obj;
		if (historialBoveda == null) {
			if (other.historialBoveda != null)
				return false;
		} else if (!historialBoveda.equals(other.historialBoveda))
			return false;
		if (monedaDenominacion == null) {
			if (other.monedaDenominacion != null)
				return false;
		} else if (!monedaDenominacion.equals(other.monedaDenominacion))
			return false;
		return true;
	}

}
