package org.model;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.NaturalId;

/**
 * DetalleHistorialCaja generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_HISTORIAL_CAJA", schema = "BDSISTEMAFINANCIERO")
public class DetalleHistorialCaja implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BigInteger idDetalleHistorialCaja;
	private MonedaDenominacion monedaDenominacion;
	private HistorialCaja historialCaja;
	private BigInteger cantidad;

	public DetalleHistorialCaja() {

	}

	@GeneratedValue
	@Id
	@Column(name = "ID_DETALLE_HISTORIAL_CAJA", unique = true, nullable = false)
	public BigInteger getIdDetalleHistorialCaja() {
		return this.idDetalleHistorialCaja;
	}

	public void setIdDetalleHistorialCaja(BigInteger idDetalleHistorialCaja) {
		this.idDetalleHistorialCaja = idDetalleHistorialCaja;
	}

	@NaturalId
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA_DENOMINACION", nullable = false, foreignKey = @ForeignKey)
	public MonedaDenominacion getMonedaDenominacion() {
		return this.monedaDenominacion;
	}

	public void setMonedaDenominacion(MonedaDenominacion monedaDenominacion) {
		this.monedaDenominacion = monedaDenominacion;
	}

	@NaturalId
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HISTORIAL_CAJA", nullable = false, foreignKey = @ForeignKey)
	public HistorialCaja getHistorialCaja() {
		return this.historialCaja;
	}

	public void setHistorialCaja(HistorialCaja historialCaja) {
		this.historialCaja = historialCaja;
	}

	@NotNull
	@DecimalMin(value = "0")
	@Digits(integer = 18, fraction = 2)
	@Column(name = "CANTIDAD", nullable = false)
	public BigInteger getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigInteger cantidad) {
		this.cantidad = cantidad;
	}

}
