package org.model;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.NaturalId;
import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Entidad generated by hbm2java
 */
@Entity
@Table(name = "ENTIDAD", schema = "BDSISTEMAFINANCIERO")
public class Entidad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BigInteger idEntidad;
	private String denominacion;
	private String abreviatura;
	private boolean estado;
	private Set transaccionBovedaOtros = new HashSet(0);

	public Entidad() {
	}

	@Id
	@Column(name = "ID_ENTIDAD", unique = true, nullable = false)
	public BigInteger getIdEntidad() {
		return this.idEntidad;
	}

	public void setIdEntidad(BigInteger idEntidad) {
		this.idEntidad = idEntidad;
	}

	@NotNull
	@NotEmpty
	@NotBlank
	@Size(min = 1, max = 100)
	@NaturalId
	@Column(name = "DENOMINACION", nullable = false, length = 100)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@NotEmpty
	@NotBlank
	@Size(min = 1, max = 20)
	@Column(name = "ABREVIATURA", nullable = false, length = 20)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@NotNull
	@Type(type = "org.hibernate.type.NumericBooleanType")
	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<TransaccionBovedaOtro> getTransaccionBovedaOtros() {
		return this.transaccionBovedaOtros;
	}

	public void setTransaccionBovedaOtros(Set transaccionBovedaOtros) {
		this.transaccionBovedaOtros = transaccionBovedaOtros;
	}

}
