package org.model;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.NaturalId;
import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * MonedaDenominacion generated by hbm2java
 */
@Entity
@Table(name = "MONEDA_DENOMINACION", schema = "BDSISTEMAFINANCIERO")
@XmlRootElement(name = "monedadenominacion")
@XmlAccessorType(XmlAccessType.NONE)
@NamedQueries({ @NamedQuery(name = MonedaDenominacion.allActive, query = "SELECT m from MonedaDenominacion m WHERE m.moneda.idMoneda = :idmoneda AND m.estado = TRUE") })
public class MonedaDenominacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public final static String allActive = "allActive";

	private BigInteger idMonedaDenominacion;
	private Moneda moneda;
	private String denominacion;
	private BigDecimal valor;
	private boolean estado;
	private Set transaccionBovedaCajaDetalls = new HashSet(0);
	private Set detalleHistorialBovedas = new HashSet(0);
	private Set transaccionBovedaOtroDetalls = new HashSet(0);
	private Set detalleHistorialCajas = new HashSet(0);

	public MonedaDenominacion() {
	}

	@XmlElement(name = "id")
	@Id
	@Column(name = "ID_MONEDA_DENOMINACION", unique = true, nullable = false)
	public BigInteger getIdMonedaDenominacion() {
		return this.idMonedaDenominacion;
	}

	public void setIdMonedaDenominacion(BigInteger idMonedaDenominacion) {
		this.idMonedaDenominacion = idMonedaDenominacion;
	}

	@XmlTransient
	@NaturalId
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA", nullable = false, foreignKey = @ForeignKey)
	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	@XmlElement(name = "denominacion")
	@NotNull
	@Size(min = 1, max = 30)
	@NotEmpty
	@NotBlank
	@Column(name = "DENOMINACION", nullable = false, length = 30)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@XmlElement(name = "valor")
	@NotNull
	@DecimalMin(value = "0", inclusive = false)
	@Digits(integer = 6, fraction = 2)
	@NaturalId
	@Column(name = "VALOR", nullable = false)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@XmlElement
	@NotNull
	@Type(type = "org.hibernate.type.NumericBooleanType")
	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "monedaDenominacion")
	public Set<TransaccionBovedaCajaDetalle> getTransaccionBovedaCajaDetalls() {
		return this.transaccionBovedaCajaDetalls;
	}

	public void setTransaccionBovedaCajaDetalls(Set transaccionBovedaCajaDetalls) {
		this.transaccionBovedaCajaDetalls = transaccionBovedaCajaDetalls;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "monedaDenominacion")
	public Set<DetalleHistorialBoveda> getDetalleHistorialBovedas() {
		return this.detalleHistorialBovedas;
	}

	public void setDetalleHistorialBovedas(Set detalleHistorialBovedas) {
		this.detalleHistorialBovedas = detalleHistorialBovedas;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "monedaDenominacion")
	public Set<TransaccionBovedaOtroDetall> getTransaccionBovedaOtroDetalls() {
		return this.transaccionBovedaOtroDetalls;
	}

	public void setTransaccionBovedaOtroDetalls(Set transaccionBovedaOtroDetalls) {
		this.transaccionBovedaOtroDetalls = transaccionBovedaOtroDetalls;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "monedaDenominacion")
	public Set<DetalleHistorialCaja> getDetalleHistorialCajas() {
		return this.detalleHistorialCajas;
	}

	public void setDetalleHistorialCajas(Set detalleHistorialCajas) {
		this.detalleHistorialCajas = detalleHistorialCajas;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((moneda == null) ? 0 : moneda.hashCode());
		result = prime * result + ((valor == null) ? 0 : valor.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof MonedaDenominacion))
			return false;
		MonedaDenominacion other = (MonedaDenominacion) obj;
		if (moneda == null) {
			if (other.moneda != null)
				return false;
		} else if (!moneda.equals(other.moneda))
			return false;
		if (valor == null) {
			if (other.valor != null)
				return false;
		} else if (!valor.equals(other.valor))
			return false;
		return true;
	}

}
