package org.model;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.NaturalId;
import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name = "PAIS", schema = "BDSISTEMAFINANCIERO")
@XmlRootElement(name = "pais")
@XmlAccessorType(XmlAccessType.NONE)
@NamedQueries({ @NamedQuery(name = Pais.findByAbreviatura, query = "SELECT p FROM Pais p WHERE p.abreviatura = :abreviatura"), @NamedQuery(name = Pais.findByCodigo, query = "SELECT p FROM Pais p WHERE p.codigo = :codigo") })
public class Pais implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public final static String findByAbreviatura = "Pais.findByAbreviatura";
	public final static String findByCodigo = "Pais.findByCodigo";

	private BigInteger idPais;
	private String denominacion;
	private String abreviatura;
	private String codigo;

	public Pais() {
	}

	@XmlElement(name = "id")
	@Id
	@Column(name = "ID_PAIS", unique = true, nullable = false)
	public BigInteger getIdPais() {
		return this.idPais;
	}

	public void setIdPais(BigInteger idTipoDocumento) {
		this.idPais = idTipoDocumento;
	}

	@XmlElement
	@NotNull
	@NotBlank
	@NotEmpty
	@Size(min = 1, max = 100)
	@Column(name = "DENOMINACION", length = 100)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@XmlElement
	@NotNull
	@NotBlank
	@NotEmpty
	@Size(min = 1, max = 5)
	@Column(name = "ABREVIATURA", length = 5)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@XmlElement
	@NotNull
	@NotBlank
	@NotEmpty
	@Size(min = 1, max = 5)
	@NaturalId
	@Column(name = "CODIGO", length = 5)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

}
